instructions = {}
instructions["generation"] = """[INST] You are a helpful and precise assistant for checking the quality of the answer.
[Question]
{question_body}

The Start of Assistant 1's Answer]
{answer1_body}

[The End of Assistant 1's Answer]

[The Start of Assistant 2's Answer]
{answer2_body}

[The End of Assistant 2's Answer]

[System]
We would like to request your feedback on the performance of two AI assistants in response to the user question displayed above.
Please rate the helpfulness, relevance, accuracy, level of details of their responses. Each assistant receives an overall score on a scale of 1 to 10, where a higher score indicates better overall performance.
Please first output a single line containing only two values indicating the scores for Assistant 1 and 2, respectively. The two scores are separated by a space. In the subsequent line, please provide a comprehensive explanation of your evaluation, avoiding any potential bias and ensuring that the order in which the responses were presented does not affect your judgment.

### Response: [/INST]"""

instructions["generation"] = """[INST]You are a helpful assistant in evaluating the quality of the outputs for a given instruction. Your goal is to select the best output for the given instruction.
Select the Output (a) or Output (b) that is better for the given instruction. The two
outputs are generated by two different AI chatbots respectively.
Do NOT provide any explanation for your choice.
Do NOT say both / neither are good.
You should answer using ONLY “Output (a)” or “Output (b)”. Do NOT output
any other words.
# Instruction:
{question_body}
# Output (a):
{answer1_body}
# Output (b):
{answer2_body}
# Which is better, Output (a) or Output (b)? Your response should be either “Output (a)” or “Output (b)”:[/INST]"""

instructions["logprobs"] = """[INST]{question_body}[/INST]{answer_body}"""
instructions["logprobs_pre"] = """[INST]{question_body}[/INST]"""